#+title: Jira Emacs integration
[[https://github.com/agzam/go-jira.el/actions/workflows/run-tests.yml][https://github.com/agzam/go-jira.el/actions/workflows/run-tests.yml/badge.svg]]

* Why ...
Because Jira UI sucks and I just can't stand it. It's a useless time wasting mental black hole that bombards my brain neurons with useless crap and I don't have time and patience to deal with it. Unfortunately, I have to use it for work.

* What ...
This is an Emacs package that works with Jira while delegating the part of auth/fetching data to [[https://github.com/go-jira/jira][go-jira]] CLI tool - hence the name.


* How ...
You can install the package through your favorite Emacs package manager, it's not published on any public repositories such as MELPA, because of its highly opinionated UI and I made it mainly to serve my own needs.

You can still grab it directly from GitHub, here's the example Doom config:

#+begin_src elisp
(package! go-jira :recipe
  (:recipe (:host github
            :repo "agzam/go-jira.el"
            :files ("*.el"))))
#+end_src

** Prerequisites
Of course you'd need go-jira CLI installed, follow [[https://github.com/go-jira/jira][the instructions]]

*** Auth
It depends on the type of Jira instance you're trying to access. The package doesn't do anything here, so you *must* sort that out with the CLI first - make sure ~jira view <SOME-TICKET-NUMBER>~ in terminal works, before trying any go-jira Emacs commands.

* Features:

- ~go-jira-popup-mode~ - shows description of a ticket when cursor is at point of a text matching Jira ticket number

  - in TUI, instead of the popup there's an option - ~go-jira-eldoc-mode~

- ~go-jira-view-ticket~ - shows the ticket description, subtasks, linked items and comments

- ~go-jira-display-board~ - consult picker that allows you to find a board and display the list of tickets on the board. 

- ~go-jira-browse-default-board~ - most of the time you'd want to quickly jump to one specific board. When you run the command for the first time, it would prompt you to pick a board from the list and sets the ~go-jira-default-board-id~.

  You can set it manually:

  1. Open your board: =M-x go-jira-browse-boards= → select “SAC Pipeline (Pod 2)”
  2. In that buffer, evaluate: =M-: go-jira--board-data RET=
  3. Look for =:id 3018= (or whatever number) in the output

- ~go-jira-add-comment~ (bound to =C= in both view and board modes) - adds comments to tickets. Write your comment in Org-mode format (with support for headings, bold, italic, code blocks, links, lists, etc.) and it will be automatically gets converted to Jira markup when submitted.
     
- Embark integration - adds Embark target so you can immediately start browsing the ticket info once cursor is on a ticket number.
